### PR TITLE
removing swagger

### PR DESCRIPTION
**Pull request by aklkv**

### CODE REVIEW

**Comment by avalonabecker** [comment]
Was testing done on this to make sure the full Docker stack works including SSO Circle, and also the local development environment running node on 3200 and Angular on 4200 still work?

**Comment by mflatscher** [comment]
> Was testing done on this to make sure the full Docker stack works including SSO Circle, and also the local development environment running node on 3200 and Angular on 4200 still work?

I have not personally tested; I approved the change request based on my understanding that this is an independent component.

Note: SSOCircle integration in full docker stack was let go in beanstalk commit dc963854a32 on 2018-08-24 because there was no way to provide the equivalent of AD groups/roles with SSOCircle, which prevented us from testing staff functionality in the full docker stack. It now behaves the same way loc-dev does in terms of passing and letting through role headers.

**Comment by avalonabecker** [comment]
@mflatscher @rosenzweigm - could one of you please test @aklkv 's work to make sure Docker is still running correctly and approve if so?

**Comment by rosenzweigm** [comment]
Local testing is successful.

**Pull request merged**
